### ISSUE TITLE
ZMQ::version exception

### ISSUE THREAD

**Issue by gdo** [chuckremes/ffi-rzmq#109]
If I do 

puts "VERSION #{ZMQ::version}"

I obtain 

/home/gdo/.rvm/gems/ruby-2.1.1/gems/ffi-rzmq-2.0.1/lib/ffi-rzmq.rb:11:in `version': uninitialized constant ZMQ::VERSION (NameError)

**Comment by chuckremes** [comment]
If you want to get the version of libzmq that is installed, run this:

```
require 'ffi-rzmq'
p LibZMQ.version
```

That will return an array of three numbers indicating the major, minor and patch version. For example, 4.0.5 will be returned as [4, 0, 5].

In the meantime, I will take your earlier suggestion to add version.rb to the load statement. ZMQ::VERSION should return the version of the gem itself.

New version of the gem will be released today/tomorrow.
