### ISSUE TITLE
Losing Messages with Router/Dealer after Dealer crashes

### ISSUE THREAD

**Issue by ds1982** [chuckremes/ffi-rzmq#111]
Hello,

i am pretty new to ZMQ and have started to play around with some Router/Dealer Examples.

My Dealer:
```ruby
require 'rubygems'
require 'ffi-rzmq'

context = ZMQ::Context.new 1

socket = context.socket ZMQ::DEALER
socket.setsockopt ZMQ::IDENTITY, "CL"
socket.connect 'tcp://localhost:5555'
string =""

while true
socket.recv_string string
puts string
end
```

My Router:
```ruby
require 'rubygems'
require 'ffi-rzmq'

context = ZMQ::Context.new 1

socket = context.socket ZMQ::ROUTER
socket.bind 'tcp://*:5555'

while true
sleep 1
puts "sending to CL"
socket.send_string "CL", ZMQ::SNDMORE
socket.send_string "This is the workload for CL"
end
```
I am experiencing the following:
It works independendly which application (Router or Dealer) i start  first. When Router crashes for some reason (CTRL-C) i can restart it and everything works fine.
When the Dealer crashes while Router is working and i restart it the Router sends the Messages without error, but they are not received again by the Dealer. 

Whats wrong here and how can i fix it?

Is Router-Dealer the right pattern for my use-case? I have 3-5 applications which need to send messages to one of the other applications depending on some external things. My idea was to bind a router and connect a dealer in every application to the same port. Is this the wrong pattern?

**Comment by chuckremes** [comment]
Not a bug in ffi-rzmq.
