### ISSUE TITLE
hwserver process hangs on ctrl-C

### ISSUE THREAD

**Issue by dlbirch** [chuckremes/ffi-rzmq#113]
Hello, I'm using jruby 1.7.13 and the latest version of ffi-rzmq on my Mac running 10.9.4.  

I'm running the hello world server (hwserver) and client (hwclient) bits (as I'm working through the book containing the same). 

I can start both the hwserver and hwclient apps ... and they both seem to work.  
Unfortunately, when I CTRL-C the hwserver (after the hwclient completes) it hangs the process and ties up the port... and I end up having to kill the process via: 

>processes | grep 'hwserver'
>kill -s kill PID_GOES_HERE

How can I change things so that when I CTRL-C the hwserver.rb app, it will not hang?

**Comment by chuckremes** [comment]
Not a bug in ffi-rzmq. Maybe the issue owner would like to send a pull request with some documentation to avoid this situation. I'll happily accept it.
