### ISSUE TITLE
Windows 7 libzmq.dll load is failing

### ISSUE THREAD

**Issue by CootCraig** [chuckremes/ffi-rzmq#120]
I may just need some help.  Looking at the error output, the necessary files are on the search path:

==== Error Output
Unable to load this gem. The libzmq library (or DLL) could not be found.
If this is a Windows platform, make sure libzmq.dll is on the PATH.
If the DLL was built with mingw, make sure the other two dependent DLLs,
libgcc_s_sjlj-1.dll and libstdc++6.dll, are also on the PATH.
For non-Windows platforms, make sure libzmq is located in this search path:
["C:/Ruby21/lib/ruby/gems/2.1.0/gems/ffi-rzmq-core-1.0.3/lib/ffi-rzmq-core/../../ext/libzmq.dll", "C:\Windows\system32/libzmq.dll", "C:\Windows/libzmq.dll", "C:\Windows\System32\Wbem/libzmq.dll", "C:\Windows\System32\WindowsPowerShell\v1.0\/libzmq.dll", "C:\0mq_dll\4.1.1\bin/libzmq.dll", "C:\Ruby21\bin/libzmq.dll", "/usr/local/lib/libzmq.dll", "/opt/local/lib/libzmq.dll", "/usr/lib64/libzmq.dll"]
C:/Ruby21/lib/ruby/gems/2.1.0/gems/ffi-rzmq-core-1.0.3/lib/ffi-rzmq-core/libzmq.rb:54:in `rescue in <module:LibZMQ>': The libzmq library (or DLL) could not be loaded (LoadError)
    from C:/Ruby21/lib/ruby/gems/2.1.0/gems/ffi-rzmq-core-1.0.3/lib/ffi-rzmq-core/libzmq.rb:9:in`module:LibZMQ'
    from C:/Ruby21/lib/ruby/gems/2.1.0/gems/ffi-rzmq-core-1.0.3/lib/ffi-rzmq-core/libzmq.rb:6:in `<top (required)>'
    from C:/Ruby21/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in`require'
    from C:/Ruby21/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from C:/Ruby21/lib/ruby/gems/2.1.0/gems/ffi-rzmq-core-1.0.3/lib/ffi-rzmq-core.rb:3:in`<top (required)>'
    from C:/Ruby21/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from C:/Ruby21/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in`require'
    from C:/Ruby21/lib/ruby/gems/2.1.0/gems/ffi-rzmq-2.0.4/lib/ffi-rzmq.rb:66:in `<top (required)>'
    from C:/Ruby21/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in`require'
    from C:/Ruby21/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from C:/Ruby21/lib/ruby/gems/2.1.0/gems/celluloid-zmq-0.16.1/lib/celluloid/zmq.rb:1:in`<top (required)>'
    from C:/Ruby21/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:135:in `require'
    from C:/Ruby21/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:135:in`rescue in require'
    from C:/Ruby21/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:144:in `require'
    from t.rb:1:in`<main>'

=== These files are present: (built with rubyinstaller devlit mingw

C:\0mq_dll\4.1.1\bin\libgcc_s_sjlj-1.dll
C:\0mq_dll\4.1.1\bin\libstc++-6.dll
C:\0mq_dll\4.1.1\bin|libzmq.dll

**Comment by chuckremes** [comment]
Does the latest release version still exhibit this problem on your system?

**Comment by chuckremes** [comment]
Closing. Works on my system. Reopen if there is a problem on other Windows systems.
