### ISSUE TITLE
ZMQ::Context finalizer hangs at program exit

### ISSUE THREAD

**Issue by cout** [chuckremes/ffi-rzmq#125]
If the ZMQ::Context finalizer is invoked while the context has open sockets, the finalizer will hang waiting for the sockets to be closed (see http://api.zeromq.org/3-2:zmq-ctx-destroy).

This can be partially worked around by modifying Socket to keep a reference to its Context, but finalizer order is not guaranteed in two cases: if neither the Socket nor the Context is reachable, or at program exit.

At least one other ZMQ language binding solves this by closing all the sockets before calling zmq_ctx_destroy (https://github.com/csrl/erlzmq/blob/master/c_src/zmq_drv.cpp).

The following program triggers the problem for me, but as with any GC-related issue, it may not trigger the problem in a different environment.

```
require 'ffi-rzmq'

def create_socket
  ctx = ZMQ::Context.new
  sock = ctx.socket(ZMQ::REQ)
  sock.setsockopt(ZMQ::LINGER, 0)
  return sock
end

sock = create_socket

# sock.close # if this line is uncommented, the program does not hang

# Force the context to be GC'd before the socket (if the program exits,
# the finalizers may be called in any order).
10.times do |i|
  a = " " * 1000
  puts "GC start #{i}"
  GC.start # program hangs here waiting on socket to be closed
  puts "GC done"
end
```

**Comment by cout** [comment]
(also, I do know this project is in maintenance mode and is not being actively developed, but I wanted to ensure that this issue is recorded somewhere public if someone else runs into it).

**Comment by chuckremes** [comment]
Interesting. I don't know that it makes sense to modify the gem to track open sockets and ensure they are all closed. This should probably just be documented as a potential problem due to the indeterminacy of finalizer order.

Would you like to write up some text for the README to document this behavior?

**Comment by chuckremes** [comment]
@cout Please see question above. Can you document this behavior?

**Comment by chuckremes** [comment]
I documented this behavior in the README. Closing ticket.
