### ISSUE TITLE
ZMQ::Context#terminate is not zeromq 3.2.x compatible

### ISSUE THREAD

**Issue by citrusmoose** [chuckremes/ffi-rzmq#130]
The method calls `LibZMQ.zmq_ctx_term` which is a zeromq 4.x method.

**Comment by chuckremes** [comment]
I'll take a look this weekend. The 3.x compatibility hasn't been very important but if I can easily support it then I will. 

Thanks for the report.

**Comment by chuckremes** [comment]
@citrusmoose Check back in an hour or so for a new release of `ffi-rzmq-core` and `ffi-rzmq` to support this.
