### ISSUE TITLE
Warning suggesting to add ostruct to gemspec of gem with ruby 3.3.5

### ISSUE THREAD

**Issue by catacs** [chuckremes/ffi-rzmq#135]
With ruby `3.3.5` I'm getting this warning:

```bash
/app/gems/gems/ffi-rzmq-2.0.7/lib/ffi-rzmq/poll_items.rb:2: warning: /usr/local/lib/ruby/3.3.0/ostruct.rb was loaded from the standard library, but will no longer be part of the default gems starting from Ruby 3.5.0.
You can add ostruct to your Gemfile or gemspec to silence this warning.
Also please contact the author of ffi-rzmq-2.0.7 to request adding ostruct into its gemspec.
```

The warning can be suppresed by just adding the gem to the app gemfile: `gem 'ostruct'`, but looks like the ideal solution would be to add the dependecy to the gemspec of the gem

**Comment by catacs** [comment]
Created a PR to support fixing the warning: https://github.com/chuckremes/ffi-rzmq/pull/136

**Comment by chuckremes** [comment]
Merged PR. Thank you!

New release will be out this week. I have some PRs to merge in an upstream gem too.
